version: '3.8'

services:
  hoarder:
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    container_name: hoarder
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - MEILI_ADDR=http://meilisearch:7700
      - BROWSER_WEB_URL=http://chrome:9222
      - DATA_DIR=/data
      # See https://docs.hoarder.app/configuration for more information
      - NEXTAUTH_SECRET=16439Bme5NAimTiLEocpv416+gtvNKF+9OYF
    depends_on:
      meilisearch:
        condition: service_started
    volumes:
      - hoarder-data:/data
    networks:
      - public

  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    container_name: chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    networks:
      - public

  meilisearch:
    image: getmeili/meilisearch:v1.6
    container_name: meilisearch
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch-data:/meili_data
    networks:
      - public

volumes:
  meilisearch-data:
    driver: local
  hoarder-data:
    driver: local

networks:
  public:
    name: public
