version: '3.8'

x-extras: &extras
  networks:
    - public
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "1"

services:
  postgresql:
    image: postgres:14
    container_name: postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    <<: *extras

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
       - pgadmin-data:/var/lib/pgadmin
    ports:
      - 8080:80
    depends_on:
      - postgresql
    <<: *extras

volumes:
  postgres-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  public:
    name: public
