global:
  scrape_interval:  15s

scrape_configs:
  - job_name: 'geth'
    static_configs:
      - targets: ['geth:9191']
  - job_name: 'beacon-node'
    static_configs:
      - targets: ['prysm-beacon:8080']
