version: "3.9"

services:
  umami-api:
    image: ghcr.io/umami-software/umami:postgresql-v2.13.2@sha256:611cacc80f53fe289f7e7bfe301032a117fb57e790c37272ee05f3b0eba690a3
    container_name: umami-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://umami:alskdjaslkdj@umami-db:5432/umami
      - DATABASE_TYPE=postgresql
      - HASH_SALT=asldkjasldkajsdlkajsd
      - APP_SECRET=aslkjdalkjdalksjdalskdjaslkasdsa
    ports:
      - 3000:3000
    networks:
      - public
    depends_on:
      umami-db:
        condition: service_healthy
    logging:
      driver: json-file
      options:
        max-size: "1m"
        max-file: "1"

  umami-db:
    image: postgres:12-alpine
    container_name: umami-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=umami
      - POSTGRES_USER=umami
      - POSTGRES_PASSWORD=alskdjaslkdj
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      - public
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  public:
    name: public
